version: '2.1'
services:
  api:
    build: .
    command: npm run watch
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: '0.0.0.0'
      DATABASE_URL: postgresql://postgres@db:5432/postgres
  db:
    image: postgres:9.6
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
